site_name: InstaNovo
site_description: Documentation for InstaNovo
site_author: InstaDeep Developers
site_url: https://instadeepai.github.io/InstaNovo/
site_dir: docs_public
repo_name: instadeepai/InstaNovo
repo_url: https://github.com/instadeepai/InstaNovo
strict: false

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: white
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  logo: assets/instanovo_logo_square.svg
  favicon: assets/instanovo_logo_square.svg
  icon:
    repo: fontawesome/brands/github
  font:
    text: Avenir Next
  features:
    - navigation.tracking # the URL is automatically updated with the active anchor
    - navigation.sections # top-level sections are rendered as groups in the sidebar
    - navigation.tabs # horizontal tabs at the top of the page
    - navigation.tabs.sticky # navigation tabs will lock below the header and always remain visible when scrolling
    - navigation.indexes # documents can be directly attached to sections
    - search.highlight # highlight search result
    - search.share # share button
    - search.suggest # smart suggestion
    - toc.integrate
    - toc.follow
    - content.code.annotate
    - navigation.top

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - autorefs
  - include-markdown
  - gen-files:
      scripts:
        - docs/gen_ref_nav.py
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [instanovo]
          options:
            docstring_style: google
            merge_init_into_class: yes
            show_submodules: no
            inherited_members: false
            show_source: false
            members_order: source
            show_if_no_docstring: true
            show_signature: true
            show_signature_annotations: true
            show_root_full_path: false
            show_root_heading: true
            docstring_section_style: spacy
  - mkdocs-jupyter:
      include_source: true
  - coverage:
      page_path: development/coverage
      html_report_dir: docs/coverage

nav:
  - Home: index.md
  - Tutorials:
      - Quick overview: tutorials/getting_started.md
      - Notebook: notebooks/getting_started_with_instanovo.ipynb
  - How-to guides:
      - Predicting: how-to/predicting.md
      - Using Custom Datasets: how-to/using_custom_datasets.md
      - Training: how-to/training.md
  - Reference:
      - CLI: reference/cli.md
      - Models: reference/models.md
      - Supported Modifications: reference/modifications.md
      - Prediction Output: reference/prediction_output.md
      - API: API/summary.md
  - Explanation:
      - Performance: explanation/performance.md
      - SpectrumDataFrame: explanation/spectrum_data_frame.md
  - Blog:
      - Introducing the next generation of InstaNovo models: blog/introducing-the-next-generation-of-instanovo-models.md
      - Introducing InstaNovo-P: blog/introducing-instanovo-p-a-de-novo-sequencing-model-for-phosphoproteomics.md
      - "Winnow: calibrated confidence and FDR control for de novo sequencing": blog/calibrated-confidence-and-fdr-control-for-de-novo-sequencing.md
  - For developers:
    - Set up a development environment: development/setup.md
    - Test Coverage: development/coverage.md
    - Test Report: development/allure.md
  - How to cite: citation.md
  - License: license.md
