# MassiveKB dataset

defaults:
  - default
  - _self_

# train_path: /mnt/instanovo-ceph/identity_splits_parquet/massivekb/*-train-*.parquet # Unshuffled
train_path: /mnt/instanovo-ceph/shuffled/massivekb/*.parquet # Shuffled
valid_path: /mnt/instanovo-ceph/identity_splits_parquet/validation_subsets/dataset-massivekb-valid-0000-0001.parquet

preshuffle_across_shards: False
