defaults:
  - instanovo
  - _self_
  - override dataset: phospho
  - override residues: phospho

report_to: neptune
run_name: instanovo_phospho_finetune
learning_rate: 5e-4 #5e-4 5e-5
train_batch_size: 256

save_model: True
model_save_folder_path: "checkpoints/instanovo-ft-phospho"
save_weights_only: False
ckpt_interval: 62_779
train_from_scratch: False
resume_checkpoint: "./checkpoints/model.ckpt"
residue_conflict_resolution: delete # delete, random, partial
