defaults:
  - instanovoplus
  - _self_

# Data paths and output location
data_path: tests/instanovo_test_resources/example_data/test_sample.mgf # type: .ipc
instanovo_plus_model: tests/instanovo_test_resources/instanovoplus/model_latest.ckpt
output_path: tests/instanovo_test_resources/instanovoplus/test_sample_preds.csv # type: .csv

max_length: 6
max_charge: 3
denovo: False

subset: 1

num_workers: 4
batch_size: 32
device: auto
fp16: True

instanovo_predictions_path:
refine: False

# Prediction columns
pred_tok_col: "predictions_tokenised"
pred_col: "predictions"
instanovo_id_col: scan_number
instanovoplus_id_col: scan_number
log_probs_col: "log_probs"
token_log_probs_col: "token_log_probs"
prediction_refine_col: "predictions_tokenised"
