defaults:
  - instanovoplus
  - _self_
  - override model: instanovoplus_unit_test
  - override dataset: unit_test
  - override residues: unit_test

run_name: instanovoplus_unit_test

# Overwritten when using Aichor
tb_summarywriter: "./logs/instanovo/instanovoplus-unit-test"

# Training parameters
num_workers: 4
warmup_iters: 480
learning_rate: 1e-3
train_batch_size: 32
grad_accumulation: 1

# Logging parameters
training_steps: 41
num_sanity_val_steps: 10
validate_before_training: False
console_logging_steps: 50
tensorboard_logging_steps: 500
use_neptune: False

# Training data parameters
train_subset: 1.0
valid_subset: 1.0

# Checkpointing parameters
save_model: True
keep_model_every_interval: False
save_accelerator_state: False
keep_accelerator_every_interval:
model_save_folder_path: tests/instanovo_test_resources/diffusion_train_test
checkpoint_metric:
checkpoint_metric_mode:
checkpoint_interval: 40
