defaults:
  - instanovoplus
  - _self_
  - override dataset: extended_massivekb
  - override residues: extended_unimod

run_name: instanovoplus_extended_massivekb

warmup_iters: 50000

train_batch_size: 128
preshuffle_shards: False # Using already shuffled shards

model_save_folder_path: "checkpoints/instanovoplus-extended-massivekb"
ckpt_interval: 50000
